/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.simuladorVentanas;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alejandro
 */
public class VentanaSubirProducto extends javax.swing.JFrame {

    DefaultTableModel modeloTablaProductos = new DefaultTableModel();

    /**
     * Creates new form SubirProducto
     */
    public VentanaSubirProducto() {
        initComponents();
        mostrarModeloTabla();
        this.setLocationRelativeTo(null);
    }

    private void mostrarModeloTabla() {
        modeloTablaProductos.addColumn("Usuario");
        modeloTablaProductos.addColumn("Producto");
        modeloTablaProductos.addColumn("Categoria");
        //Para leer el archivo
        //leerTextoProductos();

    }

    /*
    private void leerTextoProductos() {
        String cadena,fila[];

        try {
            FileReader lector = new FileReader("archivoSubirProductos.txt");
            BufferedReader lectura = new BufferedReader(lector);
            cadena = lectura.readLine();
            
            while(cadena != null){
                fila = cadena.split("%");
                modeloTablaProductos.addRow(fila);
                cadena = lectura.readLine();
            }
            
            
        } catch (FileNotFoundException ex) {
            System.err.println("ERROR, " + ex);

        } catch (IOException ex) {
            System.err.println("ERROR, " + ex);
        }
    }
        
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSubirProducto = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        etiquetaUsuario = new javax.swing.JLabel();
        cajaUsuario = new javax.swing.JTextField();
        etiquetaProducto = new javax.swing.JLabel();
        cajaProducto = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSubirProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cajaCategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelSubirProducto.setBackground(new java.awt.Color(204, 204, 255));

        btnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        btnRegresar.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        etiquetaUsuario.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        etiquetaUsuario.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaUsuario.setText("Usuario:");

        cajaUsuario.setBackground(new java.awt.Color(255, 255, 255));

        etiquetaProducto.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        etiquetaProducto.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaProducto.setText("Producto:");

        cajaProducto.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(modeloTablaProductos);
        scroll.setViewportView(jTable1);

        btnSubirProducto.setText("Subir Producto");
        btnSubirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirProductoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Categoria:");

        cajaCategoria.setBackground(new java.awt.Color(255, 255, 255));
        cajaCategoria.setForeground(new java.awt.Color(0, 0, 0));
        cajaCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agroquímicos", "Fertilizantes y Edáficos", "Fumigación" }));

        javax.swing.GroupLayout panelSubirProductoLayout = new javax.swing.GroupLayout(panelSubirProducto);
        panelSubirProducto.setLayout(panelSubirProductoLayout);
        panelSubirProductoLayout.setHorizontalGroup(
            panelSubirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubirProductoLayout.createSequentialGroup()
                .addGroup(panelSubirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSubirProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelSubirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegresar)
                            .addGroup(panelSubirProductoLayout.createSequentialGroup()
                                .addGroup(panelSubirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaUsuario)
                                    .addComponent(etiquetaProducto)
                                    .addComponent(jLabel1))
                                .addGap(33, 33, 33)
                                .addGroup(panelSubirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cajaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(143, 143, 143)
                                .addComponent(btnSubirProducto))))
                    .addGroup(panelSubirProductoLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelSubirProductoLayout.setVerticalGroup(
            panelSubirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSubirProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSubirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaUsuario)
                    .addComponent(cajaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelSubirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSubirProductoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelSubirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaProducto)
                            .addComponent(cajaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelSubirProductoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnSubirProducto)))
                .addGap(25, 25, 25)
                .addGroup(panelSubirProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cajaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnRegresar)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSubirProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSubirProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSubirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirProductoActionPerformed
        // TODO add your handling code here:
        ArchivoSubirProducto archivo = new ArchivoSubirProducto();
        archivo.crearArchivoSubirProductos();

        String usuario, producto, categoria;
        usuario = cajaUsuario.getText();
        producto = cajaProducto.getText();
        categoria = (String) cajaCategoria.getSelectedItem();

        Productos objProduc = new Productos(usuario, producto, categoria);
        String [] productosTabla = {usuario, producto, categoria};
        modeloTablaProductos.addRow(productosTabla);

        archivo.escribirTextoSubirProducto(objProduc);

        cajaUsuario.setText("");
        cajaProducto.setText("");
        
        //leerTextoProductos();
        
        
    }//GEN-LAST:event_btnSubirProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSubirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSubirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSubirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSubirProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSubirProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSubirProducto;
    private javax.swing.JComboBox<String> cajaCategoria;
    private javax.swing.JTextField cajaProducto;
    private javax.swing.JTextField cajaUsuario;
    private javax.swing.JLabel etiquetaProducto;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelSubirProducto;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
