/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.simuladorVentanas;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alejandro
 */
public class VentanaQueHacer extends javax.swing.JFrame {

    /**
     * Creates new form VentanaQueHacer
     */
    public VentanaQueHacer() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelQueHacer = new javax.swing.JPanel();
        etiquetaPresentacion = new javax.swing.JLabel();
        btnVerCatalogo = new javax.swing.JButton();
        btnContactarVendedor = new javax.swing.JButton();
        btnSubirProducto = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        imagenVerCatalogo = new javax.swing.JLabel();
        imagenContactarVendedor = new javax.swing.JLabel();
        imagenSubirProductos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelQueHacer.setBackground(new java.awt.Color(255, 255, 255));

        etiquetaPresentacion.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        etiquetaPresentacion.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaPresentacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaPresentacion.setText("COMERCIALIZACIÓN DE PRODUCTOS AGRÍCOLAS");

        btnVerCatalogo.setBackground(new java.awt.Color(204, 204, 204));
        btnVerCatalogo.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnVerCatalogo.setForeground(new java.awt.Color(0, 0, 0));
        btnVerCatalogo.setText("Ver Catálogo");
        btnVerCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCatalogoActionPerformed(evt);
            }
        });

        btnContactarVendedor.setBackground(new java.awt.Color(204, 204, 204));
        btnContactarVendedor.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnContactarVendedor.setForeground(new java.awt.Color(0, 0, 0));
        btnContactarVendedor.setText("Contactar Vendedor");
        btnContactarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactarVendedorActionPerformed(evt);
            }
        });

        btnSubirProducto.setBackground(new java.awt.Color(204, 204, 204));
        btnSubirProducto.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnSubirProducto.setForeground(new java.awt.Color(0, 0, 0));
        btnSubirProducto.setText("Subir Productos");
        btnSubirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirProductoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        imagenVerCatalogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\alejandro\\Desktop\\drive-download-20210807T170843Z-001\\Proyecto POO\\ProyectoAplicacion\\src\\main\\java\\ec\\edu\\espe\\simuladorProductoAgricolaImagenes\\imagenCatalogo.jpg")); // NOI18N

        imagenContactarVendedor.setIcon(new javax.swing.ImageIcon("C:\\Users\\alejandro\\Desktop\\drive-download-20210807T170843Z-001\\Proyecto POO\\ProyectoAplicacion\\src\\main\\java\\ec\\edu\\espe\\simuladorProductoAgricolaImagenes\\imagenComprador.png")); // NOI18N

        imagenSubirProductos.setIcon(new javax.swing.ImageIcon("C:\\Users\\alejandro\\Desktop\\drive-download-20210807T170843Z-001\\Proyecto POO\\ProyectoAplicacion\\src\\main\\java\\ec\\edu\\espe\\simuladorProductoAgricolaImagenes\\imagenSubir.png")); // NOI18N

        javax.swing.GroupLayout panelQueHacerLayout = new javax.swing.GroupLayout(panelQueHacer);
        panelQueHacer.setLayout(panelQueHacerLayout);
        panelQueHacerLayout.setHorizontalGroup(
            panelQueHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiquetaPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(panelQueHacerLayout.createSequentialGroup()
                .addGroup(panelQueHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQueHacerLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1))
                    .addGroup(panelQueHacerLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(panelQueHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVerCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagenVerCatalogo))))
                .addGap(165, 165, 165)
                .addGroup(panelQueHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenContactarVendedor)
                    .addComponent(btnContactarVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelQueHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubirProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagenSubirProductos))
                .addGap(60, 60, 60))
        );
        panelQueHacerLayout.setVerticalGroup(
            panelQueHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQueHacerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(etiquetaPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelQueHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenVerCatalogo)
                    .addComponent(imagenContactarVendedor)
                    .addComponent(imagenSubirProductos))
                .addGap(63, 63, 63)
                .addGroup(panelQueHacerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerCatalogo)
                    .addComponent(btnContactarVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubirProducto))
                .addGap(182, 182, 182)
                .addComponent(jButton1)
                .addGap(89, 89, 89))
        );

        getContentPane().add(panelQueHacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirProductoActionPerformed
        // TODO add your handling code here:
        VentanaSubirProducto sP = new VentanaSubirProducto();
        sP.setVisible(true);
        
    }//GEN-LAST:event_btnSubirProductoActionPerformed

    private void btnVerCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCatalogoActionPerformed
        // TODO add your handling code here:
        VentanaVerCatalogo vC = new VentanaVerCatalogo();
        vC.setVisible(true);
        
    }//GEN-LAST:event_btnVerCatalogoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnContactarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactarVendedorActionPerformed
        try {
            try {
                // TODO add your handling code here:
                Desktop.getDesktop().browse(new URI("https://wa.me/593983594766?text=Hola,%20quisiera%20mas%20informaci%C3%B3n%20acerca%20de%20la%20venta%20de%20Productos%20Agr%C3%ADcolas"));
            } catch (IOException ex) {
                Logger.getLogger(VentanaQueHacer.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(VentanaQueHacer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnContactarVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaQueHacer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaQueHacer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaQueHacer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaQueHacer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaQueHacer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContactarVendedor;
    private javax.swing.JButton btnSubirProducto;
    private javax.swing.JButton btnVerCatalogo;
    private javax.swing.JLabel etiquetaPresentacion;
    private javax.swing.JLabel imagenContactarVendedor;
    private javax.swing.JLabel imagenSubirProductos;
    private javax.swing.JLabel imagenVerCatalogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelQueHacer;
    // End of variables declaration//GEN-END:variables
}
