
package ec.edu.espe.simuladorVentanas;

import javax.swing.JOptionPane;

/**
 *
 * @author alejandro
 */
public class VentanaIniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaIniciarSesion
     */
    public VentanaIniciarSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSesion = new javax.swing.JPanel();
        etiquetaIniciarSesion = new javax.swing.JLabel();
        etiquetaUsuario = new javax.swing.JLabel();
        cajaUsuario = new javax.swing.JTextField();
        etiquetaContraseña = new javax.swing.JLabel();
        cajaContraseña = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        etiquetaNoCuenta = new javax.swing.JLabel();
        btnRegistrarme = new javax.swing.JButton();
        imagenInicioSesion = new javax.swing.JLabel();
        menuIniciarSesion = new javax.swing.JMenuBar();
        menuInfo = new javax.swing.JMenu();
        menuIntegrantes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelSesion.setBackground(new java.awt.Color(255, 255, 255));

        etiquetaIniciarSesion.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        etiquetaIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaIniciarSesion.setText("INICIAR SESION");

        etiquetaUsuario.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        etiquetaUsuario.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaUsuario.setText("Usuario:");

        cajaUsuario.setBackground(new java.awt.Color(255, 255, 255));

        etiquetaContraseña.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        etiquetaContraseña.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaContraseña.setText("Contraseña:");

        cajaContraseña.setBackground(new java.awt.Color(255, 255, 255));

        btnIniciarSesion.setBackground(new java.awt.Color(204, 204, 204));
        btnIniciarSesion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        etiquetaNoCuenta.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        etiquetaNoCuenta.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaNoCuenta.setText("¿Aun no tienes una cuenta?");

        btnRegistrarme.setBackground(new java.awt.Color(204, 204, 204));
        btnRegistrarme.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        btnRegistrarme.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarme.setText("Registrarme");
        btnRegistrarme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarmeActionPerformed(evt);
            }
        });

        imagenInicioSesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\alejandro\\Desktop\\drive-download-20210807T170843Z-001\\Proyecto POO\\ProyectoAplicacion\\src\\main\\java\\ec\\edu\\espe\\simuladorProductoAgricolaImagenes\\imagenLogin.jpg")); // NOI18N

        javax.swing.GroupLayout panelSesionLayout = new javax.swing.GroupLayout(panelSesion);
        panelSesion.setLayout(panelSesionLayout);
        panelSesionLayout.setHorizontalGroup(
            panelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiquetaIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSesionLayout.createSequentialGroup()
                .addGroup(panelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSesionLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaContraseña)
                            .addComponent(etiquetaUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cajaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelSesionLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnRegistrarme, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSesionLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(etiquetaNoCuenta))
                    .addGroup(panelSesionLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSesionLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(imagenInicioSesion)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        panelSesionLayout.setVerticalGroup(
            panelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSesionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(etiquetaIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imagenInicioSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaUsuario)
                    .addComponent(cajaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaContraseña)
                    .addComponent(cajaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(etiquetaNoCuenta)
                .addGap(34, 34, 34)
                .addComponent(btnRegistrarme, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        menuIniciarSesion.setBackground(new java.awt.Color(255, 255, 255));
        menuIniciarSesion.setForeground(new java.awt.Color(204, 255, 255));

        menuInfo.setText("Info");

        menuIntegrantes.setBackground(new java.awt.Color(255, 255, 255));
        menuIntegrantes.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        menuIntegrantes.setForeground(new java.awt.Color(0, 0, 0));
        menuIntegrantes.setText("Integrantes");
        menuIntegrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIntegrantesActionPerformed(evt);
            }
        });
        menuInfo.add(menuIntegrantes);

        menuIniciarSesion.add(menuInfo);

        setJMenuBar(menuIniciarSesion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
        String usuarioCorrecto, contraseñaCorrecta;
        usuarioCorrecto = "Alejandro";
        contraseñaCorrecta = "alejandro2001";
        
        if(usuarioCorrecto.equals(cajaUsuario.getText())){
            String contraseña = "";
            
            for(int i=0; i<cajaContraseña.getPassword().length; i++){
                contraseña += cajaContraseña.getPassword()[i];
            }
            
            if(contraseña.equals(contraseñaCorrecta)){
                JOptionPane.showMessageDialog(null, "Ingresaste al Sistema");
                VentanaQueHacer v2 = new VentanaQueHacer();
                v2.setVisible(true);
                dispose();
                
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Contraseña Erronea");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "ERROR, usuario desconocido");
        }
        
        cajaUsuario.setText("");
        cajaContraseña.setText("");
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnRegistrarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarmeActionPerformed
        // TODO add your handling code here:
        VentanaRegistrarse vRegistro = new VentanaRegistrarse(this, true);
        vRegistro.setVisible(true);
    }//GEN-LAST:event_btnRegistrarmeActionPerformed

    private void menuIntegrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIntegrantesActionPerformed
        // TODO add your handling code here:
        VentanaIntegrantes vI = new VentanaIntegrantes(this, true);
        vI.setVisible(true);
    }//GEN-LAST:event_menuIntegrantesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaIniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrarme;
    private javax.swing.JPasswordField cajaContraseña;
    private javax.swing.JTextField cajaUsuario;
    private javax.swing.JLabel etiquetaContraseña;
    private javax.swing.JLabel etiquetaIniciarSesion;
    private javax.swing.JLabel etiquetaNoCuenta;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JLabel imagenInicioSesion;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenuBar menuIniciarSesion;
    private javax.swing.JMenuItem menuIntegrantes;
    private javax.swing.JPanel panelSesion;
    // End of variables declaration//GEN-END:variables
}
